# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: GA小站
    url: http://www.ichdata.com/
  - name: 华Ing's blog
    url: https://wurh.github.io/
  - name: 小猪's blog
    url: http://blog.smallpig.cn/

# navigation menu
menu:
  - name: Home
    slug: home
    url: /
  - name: Archives
    slug: archives
    url: /archives
  - name: About
    slug: about
    url: /about

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true4

# use url, not username
social:
- slug: github
  url: https://github.com/wurh
- slug: facebook
  url: https://www.facebook.com/profile.php?id=100010610046396
- slug: rss
	url: /atom.xml
